// <auto-generated />
using System;
using GLORIOUSSYSTEM.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GLORIOUSSYSTEM.Data.Migrations
{
    [DbContext(typeof(HydroponicDbContext))]
    partial class HydroponicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("GLORIOUSSYSTEM.Data.Models.Actuator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("Actuators");
                });

            modelBuilder.Entity("GLORIOUSSYSTEM.Data.Models.ActuatorEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActuatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActuatorId");

                    b.ToTable("ActuatorEvents");
                });

            modelBuilder.Entity("GLORIOUSSYSTEM.Data.Models.Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Angle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("EMEET C950");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("GLORIOUSSYSTEM.Data.Models.Display", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TouchEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("Displays");
                });

            modelBuilder.Entity("GLORIOUSSYSTEM.Data.Models.LeafClassification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CameraId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PredictedClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("PipeId");

                    b.ToTable("LeafClassifications");
                });

            modelBuilder.Entity("GLORIOUSSYSTEM.Data.Models.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("GLORIOUSSYSTEM.Data.Models.Pipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("PipeNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PipeNumber" }, "IX_Pipes_PipeNumber")
                        .IsUnique();

                    b.ToTable("Pipes");
                });

            modelBuilder.Entity("GLORIOUSSYSTEM.Data.Models.Reading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SensorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SensorId", "Timestamp" }, "idx_readings_sensor_time");

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("GLORIOUSSYSTEM.Data.Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<double?>("MaxThreshold")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PositionIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("PipeId");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("GLORIOUSSYSTEM.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GLORIOUSSYSTEM.Data.Models.Actuator", b =>
                {
                    b.HasOne("GLORIOUSSYSTEM.Data.Models.Node", "Node")
                        .WithMany("Actuators")
                        .HasForeignKey("NodeId")
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("GLORIOUSSYSTEM.Data.Models.ActuatorEvent", b =>
                {
                    b.HasOne("GLORIOUSSYSTEM.Data.Models.Actuator", "Actuator")
                        .WithMany("ActuatorEvents")
                        .HasForeignKey("ActuatorId")
                        .IsRequired();

                    b.Navigation("Actuator");
                });

            modelBuilder.Entity("GLORIOUSSYSTEM.Data.Models.Display", b =>
                {
                    b.HasOne("GLORIOUSSYSTEM.Data.Models.Node", "Node")
                        .WithMany("Displays")
                        .HasForeignKey("NodeId")
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("GLORIOUSSYSTEM.Data.Models.LeafClassification", b =>
                {
                    b.HasOne("GLORIOUSSYSTEM.Data.Models.Camera", "Camera")
                        .WithMany("LeafClassifications")
                        .HasForeignKey("CameraId")
                        .IsRequired();

                    b.HasOne("GLORIOUSSYSTEM.Data.Models.Pipe", "Pipe")
                        .WithMany("LeafClassifications")
                        .HasForeignKey("PipeId");

                    b.Navigation("Camera");

                    b.Navigation("Pipe");
                });

            modelBuilder.Entity("GLORIOUSSYSTEM.Data.Models.Reading", b =>
                {
                    b.HasOne("GLORIOUSSYSTEM.Data.Models.Sensor", "Sensor")
                        .WithMany("Readings")
                        .HasForeignKey("SensorId")
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("GLORIOUSSYSTEM.Data.Models.Sensor", b =>
                {
                    b.HasOne("GLORIOUSSYSTEM.Data.Models.Node", "Node")
                        .WithMany("Sensors")
                        .HasForeignKey("NodeId")
                        .IsRequired();

                    b.HasOne("GLORIOUSSYSTEM.Data.Models.Pipe", "Pipe")
                        .WithMany("Sensors")
                        .HasForeignKey("PipeId");

                    b.Navigation("Node");

                    b.Navigation("Pipe");
                });

            modelBuilder.Entity("GLORIOUSSYSTEM.Data.Models.Actuator", b =>
                {
                    b.Navigation("ActuatorEvents");
                });

            modelBuilder.Entity("GLORIOUSSYSTEM.Data.Models.Camera", b =>
                {
                    b.Navigation("LeafClassifications");
                });

            modelBuilder.Entity("GLORIOUSSYSTEM.Data.Models.Node", b =>
                {
                    b.Navigation("Actuators");

                    b.Navigation("Displays");

                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("GLORIOUSSYSTEM.Data.Models.Pipe", b =>
                {
                    b.Navigation("LeafClassifications");

                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("GLORIOUSSYSTEM.Data.Models.Sensor", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
